config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("jd-ph-cms.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^cms/accounts/', include("jd-ph-cms.accounts.urls", namespace='accounts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permissin Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

jd-ph-cms/accounts/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

# app_name = 'accounts'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.index,
        name='account_index'
    ),
    url(
        regex=r'^something/$',
        view=views.something,
        name='account_something'
    ),
    url(
        regex=r'^edit/(?P<pk>[0-9]+)/$',
        view=views.edit,
        name='edit'
    ),

]

jd-ph-cms/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

jd-ph-cms/accounts/models.py
from decimal import Decimal
from django.db import models
from django.core.validators import MinValueValidator
from ..notifications.models import NotificationMessage
from ..users.models import User

class Answer(models.Model):
    question = models.ForeignKey('contests.contest', related_name='answer',
                                 on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    correct_answer = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.answer_text

    class Meta:
        db_table = 'cms_answer'


class Account(models.Model):
    billingpostalcode = models.CharField(max_length=20, null=True, blank=True)
    isdeleted = models.BooleanField(default=False)
    id = models.IntegerField(primary_key=True, unique=True)
    billinglatitude = models.DecimalField(
        max_digits=11,
        decimal_places=8,
        null=True,
        blank=True)
    _hc_lastop = models.CharField(max_length=32, null=True, blank=True)
    createddate = models.DateTimeField(null=True, blank=True)
    billingcountry = models.CharField(max_length=80, null=True, blank=True)
    geolocation_longitude_s = models.DecimalField(
        max_digits=11,
        decimal_places=8,
        db_column='geolocation__longitude__s',
        null=True,
        blank=True)
    geolocation_latitude_s = models.DecimalField(
        max_digits=11,
        decimal_places=8,
        db_column='geolocation__latitude__s',
        null=True,
        blank=True)
    billingstate = models.CharField(max_length=80, null=True, blank=True)
    billingstreet = models.CharField(max_length=255, null=True, blank=True)
    billinglongitude = models.DecimalField(
        max_digits=11,
        decimal_places=8,
        null=True,
        blank=True)
    billingcity = models.CharField(max_length=40, null=True, blank=True)
    systemmodstamp = models.DateTimeField(null=True, blank=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    _hc_err = models.TextField(null=True, blank=True, max_length=1024)
    sfid = models.CharField(max_length=18, null=True, blank=True)

    # these three should be on a separate model
    # schedule = models.CharField(max_length=200,null=True,blank=True)
    # timestamp = models.DateTimeField(auto_now_add=True)
    # is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        # managed = False
        db_table = 'salesforce\".\"account'
        verbose_name = 'Salesforce Account'
        verbose_name_plural = 'Salesforce Accounts'


class AccountAddon(models.Model):
    account = models.OneToOneField(Account,
                                   related_name='accountaddons',
                                   on_delete=models.CASCADE)
    schedule = models.CharField(max_length=200, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_featured = models.BooleanField(default=False)
    avg_consumer_spending = models.DecimalField(null=True, blank=True, max_digits=7, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    menu_best_sellers = models.TextField(null=True, blank=True)
    promotions = models.TextField(null=True, blank=True)
    author = models.ForeignKey(User, null=True, blank=True)
    last_update_datetime = models.DateTimeField(null=True, blank=True)
    category = models.CharField(max_length=50, null=True, blank=True)
    is_type = models.CharField(default='Account', max_length=50)

    def __str__(self):
        return str(self.account)

    @property
    def has_notif(self):
        try:
            notif_obj = NotificationMessage.objects.get(linkback = 'new_account_' + str(self.account.id))
            return True
        except NotificationMessage.DoesNotExist:
            return False

    class Meta:
        verbose_name_plural = 'Account Addons'
        db_table = 'cms_account_addon'

jd-ph-cms/contests/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils import timezone
from cloudinary.models import CloudinaryField


class Contest(models.Model):
    name = models.CharField(max_length=200)
    publish_duration_date_start = models.DateTimeField(null=True, blank=True)
    publish_duration_date_end = models.DateTimeField(null=True, blank=True)
    banner = CloudinaryField('banner')
    points = models.PositiveSmallIntegerField(default=0, blank=False, validators=[MinValueValidator(0)])
    author = models.ForeignKey('myuser.myuser', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_featured = models.BooleanField(default=False)
    is_type = models.CharField(default='Contest', max_length=50)
    is_active = models.BooleanField(default=True)
    is_published = models.BooleanField(default=False)
    category = models.CharField(
        max_length=50,
        null=True,
        blank=True,
        default='contests')
    question_title = models.TextField(max_length=300, null=True)

    def publish(self):
        self.publish_schedule = timezone.now()
        self.save()

    @property
    def image_url(self):
        if self.banner and hasattr(self.banner, 'url'):
            return self.banner.url

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Contests'
        db_table = 'cms_contest'

jd-ph-cms/accounts/forms.py
from django import forms
from .models import Account
from .models import AccountAddon


class Accounts_Form(forms.ModelForm):

    class Meta:
        model = Account
        widgets = {
                  'schedule': forms.Textarea(attrs={'rows': 2}),
                }
        fields = ('id', 'name', 'billingstreet', 'billingcity',
                  'billingstate', 'billingcountry',
                  'geolocation_longitude_s', 'geolocation_latitude_s',
                  'createddate')


class AccountsAddons_Form(forms.ModelForm):

    class Meta:
        model = AccountAddon
        fields = ('schedule', 'is_featured',
                  'avg_consumer_spending',
                  'menu_best_sellers', 'promotions',)

jd-ph-cms/productofferings/forms.py
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django import forms
from .models import ProductOffering
from cloudinary.forms import CloudinaryFileField
import cloudinary


class CustomCloudinaryField(CloudinaryFileField):
    my_default_error_messages = {
        'required': _("No file selected!")
    }
    default_error_messages = forms.FileField.default_error_messages.copy()
    default_error_messages.update(my_default_error_messages)
    def __init__(self, options=None, autosave=True, *args, **kwargs):
        self.autosave = autosave
        self.options = options or {}
        super(CustomCloudinaryField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        value = super(CloudinaryFileField, self).to_python(value)
        if not value:
            return None
        file_spec = value
        filename = "media/uploads/%s" % 'test_this_tempfile'
        fout = open(filename, 'wb')
        for chunk in file_spec.chunks():
            fout.write(chunk)
        fout.close()
        import magic
        f = magic.Magic(mime=True, uncompress=True)
        # f.from_file('testdata/test.gz')
        file_type = f.from_file(filename).decode("utf-8")[:5]
        if file_type != 'image':
            error_msg = 'Must be a valid image file type.'
            raise ValidationError(_('Invalid file type'), code='invalid')
        else:
            if not value:
                return None
            if self.autosave:
                return cloudinary.uploader.upload_image(value, **self.options)
            else:
                return value


class Product_Offerings_Form(forms.ModelForm):
    photo = CustomCloudinaryField(
        options = {
          'crop': 'limit',
          'width': '740',
          'height': '480',
          'format': 'png',
          'quality': '80',
          'tags': ['product_offerings',]
        },
      )

    class Meta:
        model = ProductOffering
        fields = ('photo', 'name', 'volume', 'price', 'is_featured',)


    def clean(self):
          cleaned_data = super(Product_Offerings_Form, self).clean()
          price = cleaned_data.get("price")
          try:
            if price < 0:
              error_msg = "Price must be a positive number"
              # raise forms.ValidationError(error_msg)
              self.add_error('price', error_msg)
          except:
            pass

jd-ph-cms/accounts/views.py
from django.http import HttpResponse
from django.db.models import Q, Sum, Count
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from .models import Account
from .models import AccountAddon
from ..productofferings.models import ProductOffering

from .forms import Accounts_Form
from .forms import AccountsAddons_Form
from ..productofferings.forms import Product_Offerings_Form

from ..utils import send_notifications


def index(request):
    # return HttpResponse('Testing lung...')
    accounts_obj = Account.objects.filter(Q(accountaddons__isnull=True)|Q(accountaddons__isnull=False)).order_by('name')
    print('Queryset: ', accounts_obj.query)
    return render(request, 'accounts/index.html', {'accounts': accounts_obj})


def something(request):
    return HttpResponse('this is something, hmmm...')


@login_required
def edit(request, pk):
    # should be already existing
    mode = ""
    account_obj = get_object_or_404(Account, pk=pk)

    box_status = 'closed'
    '''
        Instantiate account addon object first, create one if not yet existing
    '''

    try:
        account_addon_obj = AccountAddon.objects.get(account=account_obj)
        form_account_addon = AccountsAddons_Form(request.POST, instance=account_addon_obj)
    except AccountAddon.DoesNotExist:
        form_account_addon = AccountsAddons_Form(request.POST)
        account_addon_obj = form_account_addon.save(commit=False)
        account_addon_obj.account = account_obj
        account_addon_obj.author = request.user
        account_addon_obj.last_update_datetime = timezone.now()
        account_addon_obj.save()

    if request.method == 'POST':

        if 'btn_save_account_info' in request.POST:

            notif = request.POST.get('make_notif')
            '''
                revalidate new account addon user supplied values
            '''
            # form_account_addon = AccountsAddons_Form(request.POST, instance=account_addon_obj)

            if form_account_addon.is_valid():
                account_addon_obj = form_account_addon.save(commit=False)
                account_addon_obj.account = account_obj
                account_addon_obj.author = request.user
                account_addon_obj.last_update_datetime = timezone.now()
                account_addon_obj.save()
                form_account_addon = AccountsAddons_Form(instance=account_addon_obj)
                mode = 'saved'

                '''
                    create notify object if needed
                '''

                
                print('Notif: %s' % notif)

                if account_addon_obj.has_notif:
                    if notif == None:
                        print('Delete notif here')
                        send_notifications('account', account_obj, None, None, True)
                    else:
                        send_notifications('account', account_obj)
                else:
                    if notif != None:
                        send_notifications('account', account_obj)

            form_prod_offers = Product_Offerings_Form()

        elif 'btn_add_product' in request.POST:
            '''
                create product offer objects here
            '''
            form_prod_offers = Product_Offerings_Form(request.POST, request.FILES)
            
            if form_prod_offers.is_valid():
                prod_offers = form_prod_offers.save(commit=False)
                prod_offers.author = request.user
                prod_offers.account = account_obj
                prod_offers.save()
                mode = 'saved'
            else:
                box_status = 'open'


    else:
        form_account_addon = AccountsAddons_Form(instance=account_addon_obj)
        form_prod_offers = Product_Offerings_Form()
    
    form_account = Accounts_Form(instance=account_obj)
    products = ProductOffering.objects.filter(account=account_obj)

    return render(request , 'accounts/new.html',
        {'form': form_account, 'form_addon': form_account_addon, 'notif': account_addon_obj,
        'form_products_input': form_prod_offers, 'form_products': products,
        'prod_offer_box': box_status,
        'mode': mode})

jd-ph-cms/notifications/views.py
from django.shortcuts import render

# Create your views here.

jd-ph-cms/policies/views.py
from django.shortcuts import render

# Create your views here.

jd-ph-cms/productofferings/views.py
from django.shortcuts import render

# Create your views here.

jd-ph-cms/rewards/views.py
from django.shortcuts import render

# Create your views here.

jd-ph-cms/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

jd-ph-cms/templates/accounts/index.html
{% extends "base.html" %}
{% block content %}
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h2 class="box-title">Accounts</h2>
                </div><!-- /.box-header -->
                <div class="box-body">
		          <div class="col-xs-8 no-padding">
					<!-- search form -->
					<form action="#" method="get">
					  <div class="input-group">
						<input type="text" name="q" id="search_table" class="form-control" placeholder="Search..." style="margin-bottom: 6px !important;">
						<span class="input-group-btn">
						  <button type="submit" name="search" id="search-btn" class="btn btn-flat" style="margin-bottom: 6px !important;"><i class="fa fa-search"></i></button>
						</span>
					  </div>
					</form>
				  </div>
				  <div class="col-xs-4 text-right"><!-- <a href="/accounts/new" class="btn btn-primary">+ New Account</a> --></div>
				  <table class="data-tables table table-bordered table-hover">
					<thead>
					  <tr>
					    <th style="display:none;">Timestamp</th>
						<th width="30%">Name</th>
						<th width="30%">Address</th>
						<th width="20%">Schedule(s)</th>
						<th width="20%">Action</th>
					  </tr>
					</thead>
					<tbody>
					{% for account in accounts %}
					  <tr>
					    <td style="display:none;">{{ account.createddate }}</td>
						<td>{{ account.name }}</td>
						<td> {{ account.billingstreet }} {{ account.billingcity }} {{ account.billingstate }} {{ account.billingcountry }}</td>
						<td>{{ account.accountaddons.schedule }}</td>
						<td class="text-center">
						  <a href="{% url 'accounts:edit' pk=account.id %}" class="btn btn-sm btn-success"><i class="fa fa-pencil-square-o"></i> Edit</a>
						  <!-- <a class="btn btn-sm btn-danger" id="btn_del" data-target="#modal_del" data-toggle="modal" data-acct-id="{{ account.pk }}" data-acct-name="{{ account.name }}"><i class="fa fa-trash-o"></i> Delete</a> -->
						</td>
					  </tr>
					{% endfor %}
					</tbody>
				  </table>
				</div>
			  </div>
			</div>
		  </div>
{% endblock content %}

jd-ph-cms/templates/accounts/new.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h2 class="box-title">{% if request.path|slice:":14" == '/accounts/edit' %}
                Edit Account
              {% elif request.path|slice:":13" == '/accounts/new' %}
                New Account
              {% endif %}</h2>
                </div><!-- /.box-header -->
                <div class="box-body">
		          <div class="col-xs-12 no-padding">
				  
					<!-- form -->
					<form action="#" method="POST" id="form_loc_new_acct"  enctype="multipart/form-data">
						{% csrf_token %}
					  <div class="col-md-6">
					    <div class="form-group">
						  <label for="{{ form.name.id_for_label }}">Name</label>
						  {{ form.id|add_class:"hidden" }}
	                      {{ form.name|add_class:"form-control"|attr:"disabled:"|attr:"id:account_name" }}
	                      {{ form.name.errors}}
						</div>
					    <div class="form-group">
						  <label for="{{ form_addon.schedule.id_for_label }}">Schedule(s)</label>
	                      {{ form_addon.schedule|add_class:"form-control" }}
	                      {{ form_addon.schedule.errors}}
						</div>
						<div class="form-group">
						  <label for="{{ form_addon.avg_consumer_spending.id_for_label }}">Avg Meal Spending in PHP</label>
	                      {{ form_addon.avg_consumer_spending|add_class:"form-control" }}
	                      {{ form_addon.avg_consumer_spending.errors}}
						</div>
						<div class="form-group">
						  <label for="{{ form_addon.menu_best_sellers.id_for_label }}">Best Sellers</label> 
							{{ form_addon.menu_best_sellers|add_class:"textarea"|attr:"style:width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"}}
							{{ form_addon.menu_best_sellers.errors}}

						</div>
                        <div class="col-md-6">
    						<div class="form-group">
    	                      {{ form_addon.is_featured|add_class:"form-control" }}
    						  <label for="{{ form_addon.is_featured.id_for_label }}">Set as featured</label>
    	                      {{ form_addon.is_featured.errors}}
    						</div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                              <input class="form-control" id="make_notif" name="make_notif" type="checkbox" {% if notif.has_notif == True %}checked="checked"{% endif %}>
                              <label for="{{ form_addon.make_notif.id_for_label }}"> Set as New (Create Notif)</label>
                            </div>
                        </div>
					  </div>
					  <div class="col-md-6">
					    <div class="form-group">
						  <label for="account_address">Address</label>
						  <input type="text" class="form-control" name="account_address" id="account_address" value="" placeholder="Address..." disabled="">
						  {{ form.billingstreet|add_class:"hidden"|attr:"id:account_billingstreet"}}
						  {{ form.billingcity|add_class:"hidden"|attr:"id:account_billingcity"}}
						  {{ form.billingstate|add_class:"hidden"|attr:"id:account_billingstate"}}
						  {{ form.billingcountry|add_class:"hidden"|attr:"id:account_billingcountry"}}
						</div>
					    <div class="form-group">
						  <label>Map</label>
						  <div id="map" style="height: 100px;"></div>
						</div>
                        <div class="form-group">
                          <label>Promotions</label>
                          {{ form_addon.promotions|add_class:"form-control" }}
                          {{ form_addon.promotions.errors }}
                        </div>
						<div class="form-group">
						  <!-- <label for="{{ form.map_long.id_for_label }}">Long:</label> -->
	                      {{ form.geolocation_longitude_s|add_class:"form-control hidden" }}
	                      {{ form.geolocation_longitude_s.errors }}
						</div>
						<div class="form-group">
						  <!-- <label for="{{ form.map_lat.id_for_label }}">Lat:</label> -->
	                      {{ form.geolocation_latitude_s|add_class:"form-control hidden" }}
	                      {{ form.geolocation_latitude_s.errors }}
						</div>
					  </div>
					  <div class="col-md-12">
  					  	<div class="box box-default {% if prod_offer_box != 'open' %}collapsed-box{% endif %}">
  					  		<div class="box-header with-border">
  					  			<h3 class="box-title">Add Product Offerings</h3>
  					  			<div class="box-tools pull-right">
  					  				<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
  					  				<button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
  					  			</div>
  					  		</div>
  					  		<div class="box-body">
  					  			<div class="form-group">
  					  				<label for="{{ form_products_input.name.id_for_label }}">Name</label>
  					  				{{ form_products_input.name|add_class:"form-control" }}
  	                      			{{ form_products_input.name.errors}}
  	                      			{{ form_products_input.account|add_class:"hidden" }}
  	                      			{{ form_products_input.account.errors}}
  					  			</div>
  					  			<div class="form-group">
  					  				<label for="{{ form_products_input.volume.id_for_label }}">Volume</label>
  					  				{{ form_products_input.volume|add_class:"form-control" }}
  	                      			{{ form_products_input.volume.errors}}
  					  			</div>
  					  			<div class="form-group">
  					  				<label for="{{ form_products_input.price.id_for_label }}">Price</label>
  					  				{{ form_products_input.price|add_class:"form-control" }}
  	                      			{{ form_products_input.price.errors}}
  					  			</div>
  					  			<div class="form-group">
  					  				<label for="{{ form_products_input.photo.id_for_label }}">Photo</label>
  					  				{{ form_products_input.photo|add_class:"form-control"|attr:"accept:.jpg,.bmp,.png,.jpeg,.gif" }}
  	                      			{{ form_products_input.photo.errors}}
  					  			</div>
                                <div class="form-group">
                                    {{ form_products_input.is_featured|add_class:"form-control" }}
                                    <label for="{{ form_products_input.is_featured.id_for_label }}">Set as featured</label>
                                </div>
  					  		</div>
  					  		<div class="box-footer">
  					  			<button class="btn btn-primary btn-lg text-center center-block" type="submit" id="btn_add_product" name="btn_add_product"><i class="fa fa-save"></i> Add Product</button>
  					  		</div>
  					  	</div>
					  </div>
					  <div class="col-md-12">
					    <h5><strong>Product Offerings</strong></h5>
						{% for product in form_products %}
						<div class="form-group prod-offers {{ product.id }} col-md-4 col-sm-6 col-xs-12">
						  <div class="col-xs-12 col-md-4 text-center"><div style="background-image: url({{ product.photo.url|default:'' }});" class="thumb-prod img-thumbnail"></div></div>
						  <div class="col-xs-12 col-md-8 text-center">
<!-- 	  					    <label for="{{ product.product_name.id_for_label }}">Name</label> -->
                        	<div class="prod-name">{% if product.is_featured %}<i class="fa fa-fw fa-star"></i>{% endif %}{{ product.name }}</div>
                        	<div class="prod-info">{{ product.volume }}</div>
                        	<div class="prod-info">{{ product.price }}</div>
<!--                         	<button class="btn btn-block btn-danger">Delete</button> -->
                        	<a class="btn btn-sm btn-danger" id="btn_del" data-target="#modal_del" data-toggle="modal" data-acct-id="{{ product.pk }}" data-acct-name="{{ product.product_name }}"><i class="fa fa-trash-o"></i> Delete</a> 
						  </div>
						</div>
						{% endfor %}

					  </div>

					  <div class="col-md-12">
					    <div class="form-group">
						  <button class="btn btn-primary btn-lg text-center center-block" type="submit" id="btn_save_account_info" name="btn_save_account_info"><i class="fa fa-save"></i> SAVE</button>
						</div>
					  </div>
					  
					</form>
					
				  </div>
				</div>
			  </div>
			</div>
		  </div>

{% endblock content %}